<?
/**
 * Email utilities for PHP
 */

/* 
// Example
// Parameters as below
// Recipient 
$to = 'mr.allen.lee@gmail.com'; 
 
// Sender 
$from = 'admin@isat-solutions.com'; 
$fromName = 'Demo Admin'; 
 
// Email subject 
$subject = 'PDI Report';  
 
// Attachment file 
$file = "../images/PDI/103/PDI/103_PDI_1619883374.png"; 
 
// Email body content 
$htmlContent = ' 
    <h3>PDI Report for Unit 103</h3> 
    <p>This email is sent from the PHP script with attachment.</p> 
'; 


*/
/**
 * email util using default PHP mail function
 */
function sendEmailWithFileAttachmentDFT($to, $from, $fromName, $subject, $htmlContent, $attachmentFilepath) {

    $file = $attachmentFilepath;
    // Header for sender info 
    $headers = "From: $fromName"." <".$from.">"; 
        
    // Boundary  
    $semi_rand = md5(time());  
    $mime_boundary = "==Multipart_Boundary_x{$semi_rand}x";  
    
    // Headers for attachment  
    $headers .= "\nMIME-Version: 1.0\n" . "Content-Type: multipart/mixed;\n" . " boundary=\"{$mime_boundary}\""; 
    
    // Multipart boundary  
    $message = "--{$mime_boundary}\n" . "Content-Type: text/html; charset=\"UTF-8\"\n" . 
    "Content-Transfer-Encoding: 7bit\n\n" . $htmlContent . "\n\n";  
    
    // Preparing attachment 
    if(!empty($file) > 0){ 
        if(is_file($file)){ 
            $message .= "--{$mime_boundary}\n"; 
            $fp =    @fopen($file,"rb"); 
            $data =  @fread($fp,filesize($file)); 
    
            @fclose($fp); 
            $data = chunk_split(base64_encode($data)); 
            $message .= "Content-Type: application/octet-stream; name=\"".basename($file)."\"\n" .  
            "Content-Description: ".basename($file)."\n" . 
            "Content-Disposition: attachment;\n" . " filename=\"".basename($file)."\"; size=".filesize($file).";\n" .  
            "Content-Transfer-Encoding: base64\n\n" . $data . "\n\n"; 
        } 
    } 
    $message .= "--{$mime_boundary}--"; 
    $returnpath = "-f" . $from; 
    
    // Send email 
    $mail = @mail($to, $subject, $message, $headers, $returnpath);  
    
    // Email sending status 
    // echo $mail?"<h1>Email Sent to $to Successfully!</h1>":"<h1>Email sending failed.</h1>"; 
    } // function sendEmailWithFileAttachment    




    



    
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;

if (EMAIL_METHOD == 'PHPMailer'){
    require 'framework/PHPMailer/src/Exception.php';
    require 'framework/PHPMailer/src/PHPMailer.php';
    require 'framework/PHPMailer/src/SMTP.php';
}

/**
 * email util using default PHPMailer function
 * Note from, and fromName MAY NOT BE USED as this depends on the SMTP server setting. 
 */
function sendEmailWithFileAttachment($to, $from, $fromName, $subject, $htmlContent, $attachmentFilepathList) {

        //Create an instance; passing `true` enables exceptions
        $mail = new PHPMailer(true);
        
        try {
            //Server settings
            $mail->SMTPDebug = SMTP::DEBUG_OFF; // SMTP::DEBUG_SERVER;                      //Enable verbose debug output
            $mail->isSMTP();                                            //Send using SMTP
            $mail->Host       = EMAIL_HOST;//'smtp.gmail.com';                     //Set the SMTP server to send through
            $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
            $mail->Username   = EMAIL_USER; 
            $mail->Password   = EMAIL_PASSWORD; //SMTP password
            //Enable implicit TLS encryption
            $mail->SMTPSecure = EMAIL_SMTPSecure == 'TLS' ? PHPMailer::ENCRYPTION_STARTTLS : PHPMailer::ENCRYPTION_SMTPS; 
            //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`
            $mail->Port       = EMAIL_PORT; //587;//465;                                    
        
            //Recipients
            $mail->setFrom(EMAIL_USER, EMAIL_USER_NAME);
            $mail->addAddress($to);     //Add a recipient
            // $mail->addAddress('allen.lee@isat-solutions.com', 'Allen ISAT');               //Name is optional
            $mail->addReplyTo(EMAIL_USER, EMAIL_USER_NAME);

            $mail->addBCC('mr.allen.lee@gmail.com', 'Allen Lee');
            $mail->addCC('adeena@ljm.ca', 'Adeena');
            $mail->addCC('sabrina@ljm.ca', 'Sabrina');            
            // $mail->addCC('cc@example.com');
            // $mail->addBCC('bcc@example.com');
        

            foreach ($attachmentFilepathList as $attachmentFilePath){
                // echo "attachment1 =" . $attachmentFilePath . "<BR>";
                if (!file_exists(($attachmentFilePath))) {
                    // echo ("file does NOT exist<BR>");
                    continue; // if file doesn't exist, don't attach
                }

                if ($attachmentFilePath != ""){
                    //Attachments
                    $mail->addAttachment($attachmentFilePath);         //Add attachments
                    // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    //Optional name
                }
            }
        
            //Content
            $mail->isHTML(true);                                  //Set email format to HTML
            $mail->Subject = $subject;
            $mail->Body    = $htmlContent;
            // $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
        
            $mail->send();
            // echo 'Message has been sent';
        } catch (Exception $e) {
            echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
        }
}

?>
