<?php
include "config/config.phtml";
include "emailUtil.phtml";




// // Test out email feature

// echo "Testing";
$fromName   = "Allen ISAT";
$from       = "allen.lee.wealthy@gmail.com";
$subject    = "Greetings from ISAT Solution Inc.";
$headers    = "From: $fromName"." <".$from.">"; 
$message    = "Greeetings x 5! I wish you had a wonderful summer so far. Would like to follow up with you on how thinngs should go in the next most anticiptated even in the year";
$to         = 'mr.allen.lee@gmail.com';
$toName     = 'Allen Lee';
$attachmentFilepath = 'images/company-logo-small.jpg';

sendEmailWithFileAttachment(array(array($to, $toName)), array($from, $fromName), $subject, $message, array($attachmentFilepath));

// $result = @mail("allen.lee@isat-solutions.com", $subject, $message, $headers, $returnpath);  

// echo "Finish sending email result=$result";
// 

/*
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;

require 'framework/PHPMailer/src/Exception.php';
require 'framework/PHPMailer/src/PHPMailer.php';
require 'framework/PHPMailer/src/SMTP.php';

echo ("hello");


//Create an instance; passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
    $mail->isSMTP();                                            //Send using SMTP
    $mail->Host       = 'smtp.mail.yahoo.com'; //'smtp.gmail.com';                     //Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
    $mail->Username   = 'allen.lee@isat-solutions.com';//'johnny.lam.2828@gmail.com';                     //SMTP username
    $mail->Password   = 'xgseptubeepwtyqr';//'BigBird2013';                               //SMTP password
    // $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;            //Enable implicit TLS encryption
    $mail->Port       = 587;//465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

    //Recipients
    // $mail->setFrom('johnny.lam.2828@gmail.com', 'Johnny');
    $mail->setFrom('allen.lee@isat-solutions.com', 'Allen');
    $mail->addAddress('mr.allen.lee@gmail.com', 'Allen Lee');     //Add a recipient
    $mail->addAddress('allen.lee@isat-solutions.com', 'Allen ISAT');               //Name is optional
    $mail->setFrom('allen.lee@isat-solutions.com', 'Allen');
    // $mail->addReplyTo('johnny.lam.2828@gmail.com', 'Johnny');
    // $mail->addCC('cc@example.com');
    // $mail->addBCC('bcc@example.com');

    //Attachments
    // $mail->addAttachment('/var/tmp/file.tar.gz');         //Add attachments
    // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    //Optional name

    //Content
    $mail->isHTML(true);                                  //Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}*/
?>