<?
/**
 * Internal mysql wrapper to support legacy code
 */
if (!function_exists("mysql_query")){
	function mysql_query($sql, $db=""){
		global $mysqli;
		$result = mysqli_query($mysqli,$sql);

		return $result;
	}
}

if (!function_exists("mysql_data_seek")){
	function mysql_data_seek($result, $offset){
		global $mysqli;

		return $result->data_seek($offset);
	}
}

if (!function_exists("mysql_error")){
	function mysql_error(){
		global $mysqli;

		return mysqli_error($mysqli);
 	}
}

if (!function_exists("mysql_fetch_array")){
	function mysql_fetch_array($result, $arrayType = MYSQLI_ASSOC){

		return $result->fetch_array($arrayType);
 	}
}

if (!function_exists("mysql_fetch_row")){
	function mysql_fetch_row($result, $arrayType = MYSQLI_ASSOC){

		return $result->fetch_row($arrayType);
 	}
}


if (!function_exists("mysql_num_rows")){
	function mysql_num_rows($result){

		return $result->num_rows;
 	}
}


if (!function_exists("mysql_escape_string")){
	function mysql_escape_string($string){
		global $mysqli;

		return mysqli_real_escape_string($mysqli, $string);
	}
}

/**
 * Centralize function to execute sql, and log the action
 * @return object returned by mysqli_query 
 */
if (!function_exists("executeSql")){
    function &executeSql($sql, $dieOnError = true){
        global $_SERVER;
        global $db;
        global $mysqli;
        
        // debug_print_backtrace();
            
        if ($dieOnError){
            $errorHappened = 0;
            $result = mysqli_query($mysqli,$sql) or ($errorHappened = 1);
            
            if ($errorHappened){
                if (ERROR_HANDLER_ENABLED){
                    handleError ("Database error. <BR>SQL=$sql", "Database error in " . $_SERVER['PHP_SELF']. "<BR>SQL=$sql", SQL_ERROR, false);	
                } else {
                    die("Error: Database error in " . $_SERVER['PHP_SELF']. "<BR>" . mysql_error() . "<BR>SQL=$sql");
                }
            }
        }
        else {
            $result = mysqli_query($sql);
        }
        return $result;
    }
}
?>