<?php
/*
 * Created on 3-Oct-2006
 *
 * Agreemenht text includes in preview.phtml
 * This file changes between different projects
 */
?>
<table cellspacing="0" cellpadding="5" border="0" width="100%">
<tr class="header3">
<td align="center" class="header3">
TERMS AND CONDITIONS
</td>
</tr>

<tr class="blank">
<td>
<br />
<br />
<br />
<br />

I / We hereby confirm that the above List of Suite Selections represent my / our final instructions to the Hazelton Development Corporation to include these finishes in my / our suite at Highlight of Mississauga Condominiums, subject to the following conditions:

<BR/> <BR/>
I / We understand that the above selections are final and that I / we cannot change my selections once I / we have authorized them below.
<BR/> <BR/>

If I / we have chosen Options and Upgrades that consist of natural materials, I / we understand that natural materials are rarely consistent in colour or shade and some colour variation between the samples and the materials that are installed in my suite is possible.
<BR/> <BR/>

I / We understand that many suppliers have a continuous product improvement program. This means that the exact selections I / we have selected above may not then be available at the time those selections would be installed in my suite. In those circumstances, I / we authorize the Hazelton Development Corporation to use substitute materials of a similar or superior quality.
<BR/> <BR/>
<BR/> <BR/>
<table>
<tr class="blank">
    <td>
        Homeowner Signature:<BR/><BR/><BR/><BR></td><td> ___________________________________________________________<BR><BR/><BR/><BR/></td>
</tr>

<tr class="blank">
<td>
Marlene Card <BR/>
Interior Designer:<BR/><BR/><BR/><BR></td><td> ___________________________________________________________<BR><BR/><BR/><BR/></td>
</tr>

<tr class="blank">
<td>
Hazelton AUTHORIZED Representative:   <BR/><BR/><BR/></font></td><td>___________________________________________________________<BR/><BR/><BR/></td>
</tr>
</table>
</font>
</td>
</tr>
<tr class="blank">
</table>

</td>
</tr>
</table>

