<?
include "main_include.phtml";

?>
<html>
<? print_top_frame($selfPath, WEB_RESOURCE_INVERT_RELATIVE_PATH . "/", false, false); ?>

<head>
<title><?= get_project_name($PHP_SELF);?> - Login</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<script language="JavaScript">
<!--
	function setStartFocus()
	{
		if (document.getElementById)
			document.getElementById('requireStartFocus').focus();
	}
//-->
</script>

<body text="#000000" link="#0000FF" alink="#0000FF" vlink="#0000FF" bgcolor="#FFFFFF" onLoad="setStartFocus();">
<center>
<table height="100%" width="100%">
	<tr>
		<td align="center" valign="center">
			<table cellspacing="0" cellpadding="0" border="0" wssidth="700" hsseight="10">
				<td></td>
			</tr>
			<tr><td><br></td></tr>
			<tr>
				<td valign="top"align="left" width=470>
					<table cellspacing="0" cellpadding="0" border="0" width="100%" heissght="10">
						<tr>
							<td align="center"><img width=350 src="images/project-image-1200.jpg"></td>
						</tr>
						<tr>
							<td colspan=5 class="largetitle" align="center"><BR><BR><i>Welcome to the<br>
								LJM Tower Options and Upgrades Program:<br><br></i>
								<font size=5 color="#ecd788">Home Options Made Easy</font><br><br>
								<i>Please enter the login and password you were given by your <br>
								Customer Service Representative</i><br>
							</td>
						</tr>
						
						<tr>
						<td colspan=2 align="center" class="blank"><br><font color="FF0000">
						<? displayError(); ?>
						</font><br></td>
						</tr>
						<tr>
							<td>&nbsp;</td>
						</tr>
						<tr><td></td></tr>
						<form action="login.phtml" method="post" name="LoginScreen">
						
						<tr>
							<td colspan=5 align="center">
								<table>
									<tr>
										<td class="blank">Login:</td>
										<td class="blank"><input type="center" name="loginName" id="requireStartFocus" onFocus="(this.select())" size="10" maxlength="10"></td>						
									</tr>
									<tr>
										<td align="center" class="blank">Password:</td>
										<td><input type="password" name="password" size="10" maxlength="10"></td>
									</tr>
								</table>									
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
						</tr>
						<tr>
						<td colspan="2" align="center"><b><input type="submit" value="NEXT >>"></b><br>
						<br>
						<br>
						</font></td>
						</tr>	
						</form>	
								
					</table>			
				</td>				
			</tr>
			
			</table>
		</td>
	</tr>
</table>
</center>
</body>

</html>
