<?
include "main_include.phtml";

?>
<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body leftmargin=0 rightmargin=0 topmargin=0 bottommargin=0 marginwidth=2 marginheight=2>
<table border="0" cellspacing="1" cellpadding="1" >
  <tr bgcolor="#FFFFFF" valign=top> 
	<?
	$no_photos = TRUE;

		
	$optionID = $OptionID;

	// Query Choice table to list out all choices related to this optionID

	$sql = "SELECT * FROM Choice WHERE OptionID = $optionID order by Name";

	$result = mysql_query($sql) or handleError ("", "$sql <br>".mysql_error(), SQL_ERROR, true);

	while ($row = mysql_fetch_array($result)) {
		$filename = "images/" . $optionID . "_" . $row['ChoiceID'];

		if (file_exists($filename))
		{
			echo "<td valign=top><a href=\"\" onMouseOver=\"parent.photo_main.document.main_photo.src='$filename'\"><img src=\"$filename\" border=0 width=50 height=50></a></td>\n";
		}
	}

	?>
  </tr>
</table>
</body>
</html>
