<?
$not_include_javascript = 1;
include "main_include.phtml";

// for action is progress
$content = '[
        { "unit": "201", "PDIDone": 0, "PDIOS": 3, "PDISignedOff": 1 },
        { "unit": "221", "PDIDone": 5, "PDIOS": 13, "PDISignedOff": 5 },
        { "unit": "203", "PDIDone": 10, "PDIOS": 33, "PDISignedOff": 10 }
]';

// action is report 
// [{"Unit":201,"UnitDefectID":6,"DefectName":"Hardware - Missing strike plate in door jamb","DefectType":"PDI","SectionName":"BATHROOM - ALL","ContractorName":"LJM Carpentry","TradeContacted":0,"imageName":"..\/images\/PDI\/PDI_1726584365","hasImage":1,"ReportDate":"2024-09-17","FixedDate":"0000-00-00","ContractorID":"Contractor9","PDIDefectID":109}]

// Action is update
// Field is TradeNote
// https://yasur.pair.com/lmark/ljm/ljmtower7/RealEstateHomeOptionsDB/admin/pdiService.phtml?action=update&field=TradeNote&TradeNote=Iamsilly&PDIDefectID=7207

header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");

// echo $content;

function getPDIAgeList($unitNumber = "")
{
        global $db;

        //Prepare associated array with the age
        $PDIAgeList = array();
        $PDIAgeSql = "select UnitNumber, DATEDIFF(CURDate(),Min(PDIDefect.PDIReportDate)) AS Age 
                        from PDIDefect where PDIFixed = 0 and PDIDefect.PDIReportDate > 0 
                        group by UnitNumber";

        $PDIAgeResult = mysql_query($PDIAgeSql, $db) or die("Error : $PDIAgeSql<br>" . mysql_error());
        while ($row = mysql_fetch_array($PDIAgeResult)) {
                $PDIAgeList[$row['UnitNumber']] = $row['Age'];
        }

        // print ("PDIAgeList=[". json_encode($PDIAgeList) . "]");

        return $PDIAgeList;
} // getPDIAgeList

function getPDIProgress($unitNumber = "")
{

        global $db;

        $sql = "select Unit.UnitNumber, sum(PDIDefect.PDIDefect) AS PDITotal, 
        sum(PDIDefect.PDIFixed) AS PDIFixed,  sum(PDIDefect.PDIDefect)- sum(PDIDefect.PDIFixed) AS PDIOS,
        sum(PDIDefect.PDISignoff) AS PDISignedOff, 
        sum(PDIDefect.Day30Defect) AS Day30Total, sum(PDIDefect.Day30Fixed) AS Day30Fixed,
        sum(PDIDefect.Day30Defect) - sum(PDIDefect.Day30Fixed) AS Day30OS,
        sum(PDIDefect.Day30Signoff) AS Day30SignedOff 
        from Unit LEFT JOIN PDIDefect ON PDIDefect.UnitNumber=Unit.UnitNumber";


        if ($unitNumber != "") {
                $sql .= " WHERE Unit.UnitNumber=$unitNumber";
        }

        $sql .= " group by Unit.UnitNumber ";

        // order by casting unit number as number
        $sql .= " order by " . getOrderClause(array("tableName" => "Unit", "columnName" => "UnitNumber", "sortMethod" => DB_SORT_METHOD_VARCHAR_AS_NUMBER));


        $result = mysql_query($sql, $db) or die("Error : $sql<br>" . mysql_error());


        $PDIAgeList = getPDIAgeList($unitNumber);

        // > 21 is red, 14 < yellow < 21, others is green
        DEFINE("PDI_STATUS_RED", 21);
        DEFINE("PDI_STATUS_YELLOW", 14);
        DEFINE("PDI_STATUS_GREEN", 0);

        $content = array();
        while ($row = mysql_fetch_array($result)) {
                $resultRow                      = array();
                $resultRow['Unit']              = $row['UnitNumber'];
                $resultRow['PDITotal']          = $row['PDITotal'] ?? 0;
                $resultRow['PDIOS']             = $row['PDIOS'] ?? 0;
                $resultRow['PDIFixed']          = $row['PDIFixed'] ?? 0;
                $resultRow['PDISignedOff']      = $row['PDISignedOff'] ?? 0;
                $resultRow['PDIUnresolvedAge']  = $PDIAgeList[$row['UnitNumber']] ?? 0;
                $resultRow['PDIStatusColor']    = ($resultRow['PDIUnresolvedAge'] >= PDI_STATUS_RED) ? "red" : (($resultRow['PDIUnresolvedAge'] >= PDI_STATUS_YELLOW)  ? "yellow" : "green");


                $resultRow['Day30Total']        = $row['Day30Total'] ?? 0;
                $resultRow['Day30OS']           = $row['Day30OS'] ?? 0;
                $resultRow['Day30Fixed']        = $row['Day30Fixed'] ?? 0;
                $resultRow['Dat30SignedOff']    = $row['Day30SignedOff'] ?? 0;

                array_push($content, $resultRow);
        } // While

        echo json_encode($content, JSON_NUMERIC_CHECK);
} // getPDIProgress


function getPDIReport($unitNumber = "")
{

        global $db;
        global $_GET;



        $values                        = $_GET;
        $searchCriteria = "";
        $sqlCond                 = "";
        $hasSearchValue         = false;
        //loop that adds the field names and values
        // Exptecting the search field has format Search_XXXXX, where XXXXX is the field name
        foreach ($values as $key => $val) {
                $search_field         = $key;

                // $pos = strpos($key, "_");
                // if ($pos > 0) {
                //         if ($val != "") {
                //                 $hasSearchValue = true;
                //                 $search_field = substr($key, $pos + 1);
                //         }
                // }

                if ($search_field == "unit") {
                        //$sqlCond .= " AND UnitNumber=$val";	
                        if ($val != ""){
                                $sqlCond .= " AND (" . expandSearchCriteria(array("columnName" => "UnitNumber", "csvValue" => $val, "intervalDelimiter" => "-")) . ") ";
                        }
                }

                if ($search_field == "contractorID") {
                        if ($val != "0" && $val != "" && $val != "All") {
                                $sqlCond .= " AND ContractorID='$val'";
                        }
                }

                if ($search_field == "tradeContacted") {
                        if ($val != "" && $val != "All") {
                                if ($val == "0" || $val == "1")
                                        $sqlCond .= " AND TradeContacted='$val'";
                        }
                }

                if ($search_field == "fixed") {
                        if ($val != "" && $val != "All") {
                                if ($val == "0" || $val == "1")
                                        $sqlCond .= " AND Fixed='$val'";
                        }
                }                

                if ($search_field == "floor") {
                        if ($val != "" and IsNumeric($val))
                                $sqlCond .= " AND substring(UnitNumber, 1, length(UnitNumber)-2) = $val";
                }

                $searchCriteria .= "&" . $key . "=" . $val;
        }

        $PDISql = "SELECT * FROM
                                (SELECT UnitNumber,UnitDefectID, DefectName, DefectType, 
                                        IF ((SectionName is NULL), 'NA', SectionName) As SectionName, 
                                        IF ((ContractorName is NULL), 'NA', ContractorName) As ContractorName, 
                                        TradeContacted,
                                        imageName, hasImage,
                                        (CASE   WHEN DefectType = 'QA'          THEN QAReportDate
                                                        WHEN DefectType = 'PDI'         THEN PDIReportDate
                                                        WHEN DefectType = 'DAY30'       THEN day30ReportDate
                                                        WHEN DefectType = 'MONTH11'     THEN month11ReportDate
                                        END) As ReportDate,
                                        (CASE   WHEN DefectType = 'QA'          THEN QAFixedDate
                                                        WHEN DefectType = 'PDI'         THEN PDIFixedDate
                                                        WHEN DefectType = 'DAY30'       THEN day30FixedDate
                                                        WHEN DefectType = 'MONTH11'     THEN month11FixedDate
                                        END) As FixedDate, 
                                        (CASE   WHEN DefectType = 'QA'          THEN QAFixed
                                                        WHEN DefectType = 'PDI'         THEN PDIFixed
                                                        WHEN DefectType = 'DAY30'       THEN day30Fixed
                                                        WHEN DefectType = 'MONTH11'     THEN month11Fixed
                                        END) As Fixed, 

                                        ContractorID, PDIDefectID, TradeNote
                                        FROM
                                        (SELECT PDIDefect.*, CONCAT (PDICategory.Name, ' - ' , PDIType.Name) as DefectName, Section.Name as SectionName, Contractor.ContractorName,
                                                (CASE   WHEN (PDIDefect.PDIDefect = 1 ) THEN 'PDI'
                                                     WHEN (PDIDefect.day30Defect = 1 ) THEN 'DAY30'
                                                     WHEN (PDIDefect.QADefect = 1 ) THEN 'QA'
                                                     WHEN (PDIDefect.month11Defect = 1 ) THEN 'MONTH11'
                                                     END) AS DefectType
                                        FROM PDIDefect
                                        LEFT JOIN Section
                                        ON PDIDefect.SectionID = Section.SectionID
                                        LEFT JOIN Contractor
                                        ON PDIDefect.ContractorID = Contractor.ContractorID
                                        LEFT JOIN PDIType
                                        ON PDIDefect.PDITypeID  = PDIType.PDITypeID
                                        LEFT JOIN PDICategory
                                        ON PDIDefect.PDICatID   = PDICategory.PDICatID
                                        WHERE ((PDIDefect.PDIDefect = 1)
                                        OR (PDIDefect.day30Defect = 1 )
                                        OR (PDIDefect.QADefect = 1 )
                                        OR (PDIDefect.month11Defect = 1 ))
                                         ) A
                                ) B ";

        $PDISql .= " WHERE 1=1 ";
        $PDISql .= $sqlCond;

        $PDISql .= " ORDER BY B.UnitNumber,  B.SectionName, B.ReportDate";
        $sql    = $PDISql;

        $result = mysql_query($sql, $db) or die("Error : $sql<br>" . mysql_error());



        $content = array();
        while ($row = mysql_fetch_array($result)) {
                $resultRow                      = array();

                $resultRow['Unit']              = $row['UnitNumber'];
                $resultRow['UnitDefectID']      = $row['UnitDefectID'] ?? 0;
                $resultRow['DefectName']        = $row['DefectName'] ?? 0;
                $resultRow['DefectType']        = $row['DefectType'] ?? 0;
                $resultRow['SectionName']       = $row['SectionName'] ?? 0;
                $resultRow['ContractorName']    = $row['ContractorName'] ?? 0;
                $resultRow['TradeContacted']    = $row['TradeContacted'] ?? 0;
                $resultRow['TradeNote']         = $row['TradeNote'] ?? 0;
                $resultRow['imageName']         = $row['imageName'] ?? 0;
                $resultRow['hasImage']          = $row['hasImage'] ?? 0;
                $resultRow['ContractorName']    = $row['ContractorName'] ?? 0;
                $resultRow['ReportDate']        = $row['ReportDate'] ?? 0;
                $resultRow['FixedDate']         = $row['FixedDate'] ?? 0;
                $resultRow['Fixed']             = ($row['Fixed'] ?? 0) == 1 ? "Yes" : "No";
                $resultRow['ContractorID']      = $row['ContractorID'] ?? 0;
                $resultRow['PDIDefectID']       = $row['PDIDefectID'] ?? 0;

                array_push($content, $resultRow);
        } // While

        echo json_encode($content, JSON_NUMERIC_CHECK);
} // getPDIReport


function updatePDIDefect($unitNumber){
        global $db;
        global $_GET;

        $values = $_POST; // change to post 
        
        $updateClause    = "";

        $tradeNote      = $values['TradeNote'];
        if ($tradeNote != ""){
                if ($updateClause != "") $updateClause .= ", ";
                $updateClause    .= " TradeNote='" . $tradeNote . "'";
        }

        $PDIDefectID    = $values['PDIDefectID'];

        
        if ($PDIDefectID == ""){
                $row_result = array();
                $row_result["status"]   = "Error";
                $row_result["message"]  = "Missing PDIDefectID";

                echo json_encode($row_result, JSON_NUMERIC_CHECK);
                exit;                
        }

        $updateSql      = "UPDATE PDIDefect SET " . $updateClause . " WHERE PDIDefectID=" . $PDIDefectID;
        if (mysql_query($updateSql, $db)) {
                $row_result = array();
                $row_result["status"]   = "Success";
                $row_result["message"]  = "Record updated successfully";
                $row_result["sql"]      = $updateSql;
                echo json_encode($row_result, JSON_NUMERIC_CHECK);
                exit;

        } else {
                $row_result = array();
                $row_result["status"]   = "Error";
                $row_result["sql"]      = $updateSql;
                $row_result["message"]  = "Record cannot be updated";

                $row_result['error']    = mysql_error();
                echo json_encode($row_result, JSON_NUMERIC_CHECK);
                exit;

        }
} // updatePDIDefect

if ($action == "progress") {
        getPDIProgress($unitNumber);
} elseif ($action == "report") {
        getPDIReport($unitNumber);
} elseif ($action == "update") {
        if ($field == "TradeNote"){
                updatePDIDefect($unitNumber);
        }
}
