<?
// This script creates 4 PDI reports: Suite Report; Floor Report; Trade Unit Report; Trade Floor Report

// Param
// output - html (default), CSV
// listall

$output = $_GET['output'];

$generateReportMode = false;
// if output is CSV, don't print any javascript
if ($output == "CSV" ||  $output == "PDF") {
        $not_include_javascript = 1;
        $generateReportMode = true;
} else {
        $generateReportMode = false;
}

include "../admin/main_include.phtml";  



// if output is CSV, don't print any header
if (!$generateReportMode) {
        print_header("PDI Reports");        
        print_top_frame($PHP_SELF, SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/");
?>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
        <script src="https://code.jquery.com/ui/1.14.0/jquery-ui.js"></script>
        <script src="report_pdi_others.js"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css">
        <script type="text/javascript"  src="https:///cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>

    <script language="JavaScript">
    <!--
        function dump_CSV() {
            var form = document.getElementById("search_purchaser");
            form.innerHTML += "<INPUT ID=\"output\" TYPE=\"HIDDEN\" NAME=\"output\" VALUE=\"CSV\">";
            form.submit();

            var outputEle = document.getElementById("output");
            outputEle.remove();
        }
        function dump_PDF() {
            var form = document.getElementById("search_purchaser");
            form.innerHTML += "<INPUT TYPE=\"HIDDEN\" NAME=\"output\" VALUE=\"PDF\">";
            form.submit();
            var outputEle = document.getElementById("output");
            outputEle.remove();

        }
    //-->
    </script>
<?
}

// Handle update request on PDIDefect -> TradeContacted
if ($update) {
        // ALLEN Only update the one being unchecked
        //$sql = "UPDATE PDIDefect SET TradeContacted=0";
        //$result = mysql_query($sql,$db) or die("Error : $sql<br>" . mysql_error());
        // Add a hidden value in before CheckBox to let HTML code to send false value even
        // checkbox is not checked
        foreach ($_POST as $key=>$value) {
                echo("key=$key value=$value<BR>");
                $updateValue = 0;

                $data = explode("_", $key);
                if ($data[0] == 'TradeContacted') {
                    //print ("key=" . $key . " value=" . $value);
                        if ($value == "on") {
                            $updateValue = 1;
                        } 
                        $PDIDefect_id = $data[1];
                        $sql = "UPDATE PDIDefect SET TradeContacted=" . $updateValue . " WHERE PDIDefectID=".$PDIDefect_id;
                        $result = mysql_query($sql,$db) or die("Error : $sql<br>" . mysql_error());
                        echo("sql=$sql<BR>");
                }
        }
        die("End of foreach");
}


// Search Feature
if (!isSet($listall)) // if not list all records, use the search criteria to do the search
{
        $values			= $_GET;
        $searchCriteria = "";
	    $sqlCond 		= "";
        $hasSearchValue 	= false;
        //loop that adds the field names and values
        // Exptecting the search field has format Search_XXXXX, where XXXXX is the field name
        foreach($values as $key=>$val)
        {
		$search_field 	= $key;

                $pos = strpos($key, "_");
                if ($pos > 0)
                {
                        if ($val != "")
                        {
                                $hasSearchValue = true;
                                $search_field = substr($key, $pos + 1);
			}
		}

		if ($search_field == "UnitNumber") {
			//$sqlCond .= " AND UnitNumber=$val";	
			$sqlCond .= " AND (" . expandSearchCriteria(array("columnName"=>"UnitNumber", "csvValue"=>$val, "intervalDelimiter"=>"-")) . ") ";
		}

		if ($search_field == "ContractorID") {
			if ($val != "0") {
				$sqlCond .= " AND ContractorID='$val'";
			}
		}

                if ($search_field == "TradeContacted") {
                        if ($val != ""){
                                if ($val=="0" || $val=="1")
                                $sqlCond .= " AND TradeContacted='$val'";
                        }
                }

                if ($search_field == "Floor"){
                        if ($val != "" AND IsNumeric($val))
                        $sqlCond .= " AND substring(UnitNumber, 1, length(UnitNumber)-2) = $val";
                }

		$searchCriteria .= "&" . $key . "=" . $val;
	}
}

        $PDISql = "SELECT * FROM
                                (SELECT UnitNumber,UnitDefectID, DefectName, DefectType, SectionName, ContractorName, TradeContacted,
                                        imageName, hasImage,
                                        (CASE   WHEN DefectType = 'QA'          THEN QAReportDate
                                                        WHEN DefectType = 'PDI'         THEN PDIReportDate
                                                        WHEN DefectType = 'DAY30'       THEN day30ReportDate
                                                        WHEN DefectType = 'MONTH11'     THEN month11ReportDate
                                        END) As ReportDate,
                                        (CASE   WHEN DefectType = 'QA'          THEN QAFixedDate
                                                        WHEN DefectType = 'PDI'         THEN PDIFixedDate
                                                        WHEN DefectType = 'DAY30'       THEN day30FixedDate
                                                        WHEN DefectType = 'MONTH11'     THEN month11FixedDate
                                        END) As FixedDate, ContractorID, PDIDefectID
                                        FROM
                                        (SELECT PDIDefect.*, CONCAT (PDICategory.Name, ' - ' , PDIType.Name) as DefectName, Section.Name as SectionName, Contractor.ContractorName,
                                                (CASE   WHEN (PDIDefect.PDIDefect = 1 and PDIDefect.PDIFixed != 1) THEN 'PDI'
                                                     WHEN (PDIDefect.day30Defect = 1 and PDIDefect.day30Fixed != 1) THEN 'DAY30'
                                                     WHEN (PDIDefect.QADefect = 1 and PDIDefect.QAFixed != 1) THEN 'QA'
                                                     WHEN (PDIDefect.month11Defect = 1 and PDIDefect.month11Fixed != 1) THEN 'MONTH11'
                                                     END) AS DefectType
                                        FROM PDIDefect
                                        LEFT JOIN Section
                                        ON PDIDefect.SectionID = Section.SectionID
                                        LEFT JOIN Contractor
                                        ON PDIDefect.ContractorID = Contractor.ContractorID
                                        LEFT JOIN PDIType
                                        ON PDIDefect.PDITypeID  = PDIType.PDITypeID
                                        LEFT JOIN PDICategory
                                        ON PDIDefect.PDICatID   = PDICategory.PDICatID
                                        WHERE ((PDIDefect.PDIDefect = 1 and PDIDefect.PDIFixed != 1)
                                        OR (PDIDefect.day30Defect = 1 and PDIDefect.day30Fixed != 1)
                                        OR (PDIDefect.QADefect = 1 and PDIDefect.QAFixed != 1)
                                        OR (PDIDefect.month11Defect = 1 and PDIDefect.month11Fixed != 1))
                                         ) A
                                ) B ";

	$PDISql .= " WHERE 1=1 ";
	$PDISql .= $sqlCond;
	
	$PDISql .= " ORDER BY B.UnitNumber,  B.SectionName, B.ReportDate";

	// die("PDISql=$PDISql");

        if ($output == "CSV") {
                $sql = $PDISql;
                $filename = "report_pdi_details.csv";
                require "../../RealEstateDB/dumpCSVSql.phtml";
                die();
        } else if ($output == "PDF") {
                // die("PDISql=[" . $PDISql . "]");
                require "generatePDIDetailsPDF.phtml";
                generatePDF($PDISql);
        } 

?>
<html>


<body text="#000000" link="#0000FF" alink="#0000FF" vlink="#0000FF" bgcolor="#FFFFFF">

<BR><BR>
<DIV id="search" name="search" class="container">
<?
createCollapsibleDIVIcon("Search Criteria", "SearchCriteriaDIV");
createCollapsibleDIV("SearchCriteriaDIV");
?>
        <FORM NAME="search_purchaser" ID="search_purchaser" METHOD="GET" ACTION="<?= $PHP_SELF; ?>">
                <TABLE>
                <INPUT TYPE="HIDDEN" NAME="orderby" VALUE="<?= $orderby;?>">
                
                <TR CLASS="blank">
                        <TD>Suite Number: <BR>e.g. PH%, 100-120,127,129</TD>
                        <TD><INPUT TYPE="TEXT" NAME="search_UnitNumber" VALUE="<?= $search_UnitNumber; ?>"></TD>
                        <TD>Floor:
                        <INPUT TYPE="TEXT" NAME="search_Floor" VALUE="<?= $search_Floor;?>"></TD>
                        <!-- <OPTION  -->
                </TR>
                <TR CLASS="BLANK">
			<TD>Trade</TD>
			<TD><select name="search_ContractorID" onChange="change_link('trade_unit')">
                    <OPTION VALUE="0">All</OPTION>
<?
                // listed all contractor names in dropdown listbox
		// all the available contractors, prepared for the listbox of contractors
		$sql_Contractor = "SELECT ContractorID, ContractorName FROM Contractor
				WHERE ContractorName != ''
				ORDER BY ContractorName";
		$result_Contractor = mysql_query($sql_Contractor,$db) or die("Error : $sql_Contractor<br>" . mysql_error());
                mysql_data_seek($result_Contractor, 0);
                while ($row_Contractor = mysql_fetch_array($result_Contractor))
                {
?>
                    <OPTION VALUE="<?= $row_Contractor['ContractorID'] ?>" <?
			if ($row_Contractor['ContractorID'] == $search_ContractorID) {
				echo " SELECTED ";
			}
			?>><?= $row_Contractor['ContractorName']?> </OPTION>
<?
                }
?>
			 </TD>
                         <TD>Trade Contacted  
                         <select name="search_TradeContacted">
                                <OPTION VALUE=" ">All</OPTION>
                                <OPTION VALUE="0" <?= $search_TradeContacted=="0" ? "selected" : ""; ?>>Not Contacted</OPTION>
                                <OPTION VALUE="1" <?= $search_TradeContacted=="1" ? "selected" : ""; ?>>Contacted</OPTION>
                         </select>

                         </select>
                        </td>
                </TR>
		<TR><TD><BR></TD</TR>
		<TR>
                        <TD COLSPAN="5" ALIGN="LEFT" CLASS="blank">
				<INPUT TYPE="SUBMIT" VALUE="Search">
			
                <INPUT TYPE="BUTTON" VALUE="DOWNLOAD CSV" onClick='dump_CSV()'>
                <INPUT TYPE="BUTTON" VALUE="DOWNLOAD PDF" onClick='dump_PDF()'>
            </TD>
		</TR>
		</TABLE>
	</FORM>
	</DIV>
</DIV>


  <form name="form_PDIdefectByFloor" method="post" action="<?echo  $_SERVER["PHP_SELF"] . '?search_Floor=' . $search_Floor . '&search_ContractorID=' . $search_ContractorID . '&search_UnitNumber=' . $search_UnitNumber ; ?>">
  <div class="container">
  <table id="report-content" name="report-content" class="table table-hover table-responsive" >
<?

//
// Floor report: Report of All Defects on the XXth Floor or Floor == "all"
//

// If search_Floor is not set, then set to "all"
if (!isset($search_Floor)) {
	$search_Floor = "all";
}

// A String to store all hidden value, and echo it after table completes
$hiddenValueString = "";
?>
    <!-- <tr class="head">
      <td colspan="9">
        <b>All Defects on Floor  <?= $floor ?></b><br><br>
      </td>
    </tr> -->

<? 
	// Extract PDI Result
        $PDIresult = mysql_query($PDISql,$db) or die("Error : $PDISql<br>" . mysql_error());
        if (mysql_num_rows($PDIresult) == 0)
        {
?>
    <!-- <tr class="head">
      <td>
        No defect data found on the floor <?= $search_Floor ?>.
      </td>
    </tr> -->

<?
        }
        else
        {
                // table header
                // echo "<input type='hidden' value='".$search_Floor."' name='search_Floor'>";
                echo "<thead><tr>\n";
                echo "  <th align='center' class='head'>Unit</th>\n";
                echo "  <th align='center' class='head'>Defect ID</th>\n";
                echo "  <th align='center' class='head'>Image</th>\n";
                echo "  <th align='center' class='head'>Defect Description</th>\n";
                echo "  <th align='center' class='head'>Defect Type</th>\n";
                echo "  <th align='center' class='head'>Room</th>";
                echo "  <th align='center' class='head'>Trade Assigned</th>\n";
                echo "  <th align='center' class='head' nowrap>Report Date</th>\n";
                echo "  <th align='center' class='head'>Schedule Fix Date</th>\n";
                echo "  <th align='center' class='head'>Trade Contacted &nbsp; <input type='checkbox' id='TradeContactedAll' /></th>\n";
                echo "</tr></thead>\n\n";
                echo "<tbody>\n\n";


                $curr_unit = 0;
                while ($row = mysql_fetch_array($PDIresult))
                {
                        // if (substr($row["UnitNumber"], 0, strlen($row["UnitNumber"]) - 2) == $search_Floor || $search_Floor == "all")
                        // {
                                // print a blank line to stand out different unit
                                if ($curr_unit == 0)
                                        $curr_unit = $row["UnitNumber"];
                                elseif ($curr_unit != $row["UnitNumber"])
                                {
                                        // echo "<tr><td colspan='8'>&nbsp;</td></tr>\n\n";
                                        $curr_unit = $row["UnitNumber"];
                                }

                                echo "<tr class='table_rec'>\n";
                                echo "  <td>" . $row["UnitNumber"] . "</td>\n";
                                echo "  <td align='center'>" . $row["UnitDefectID"] . "</td>\n";
                                echo "  <td><img class='lazy rounded' width=128 height=128 data-src='" . $row['imageName'] . "'></td>\n";
                                echo "  <td>" . $row["DefectName"] . "</td>\n";
                                echo "  <td>" . $row["DefectType"] . "</td>\n";
                                echo "  <td>" . $row["SectionName"] . "</td>\n";
                                echo "  <td>" . $row["ContractorName"] . "</td>\n";
                                echo "  <td>" . $row["ReportDate"] . "</td>\n";
                                echo "  <td>" . $row["FixedDate"] . "</td>\n";
                                $hiddenValueString .= "<input type='hidden' name='TradeContacted_" . $row["PDIDefectID"] . "' value='false'>";

                                echo "  <td align='center'><input type='checkbox' name='TradeContacted_" . $row["PDIDefectID"] . "'";
                                if ($row['TradeContacted']) { echo " checked='checked'"; }
                                echo "></td>\n";
                                echo "</tr>\n\n";
                        // }
                }
        }

?>
        </tbody>
</table>
</div>
                        <!-- echo "<tr><td colspan='5'>\n"; -->
<?      echo $hiddenValueString;?>
        <input type='submit' value='Update' name='update' size='50' style='margin-right:1em'>
        <input type='submit' value='Cancel' name='cancel' size='50'>
                <!-- echo "</td></tr>\n"; -->
</form>
        <!-- MUST put the js right above the lazy handling code, otherwsie won't work -->
        <script src = "../../RealEstateDB/framework/jquerylazy/jquery.lazy.min.js"></script>
        <script src = "../../RealEstateDB/framework/jquerylazy/jquery.lazy.plugins.min.js"></script>
    <script>
        
        $(function($) {
                $("img.lazy").Lazy({    
        // your configuration goes here
                        // scrollDirection: 'vertical',
                        effect: "fadeIn",
                        effectTime: 1000,
                        threshold: 0,        
                        visibleOnly: true,
                        onError: function(element) {
                                console.log('error loading ' + element.data('src'));
                        },
                        afterLoad: function(element) {
                                  // called after an element was successfully handled
                                console.log('Finish loading ' + JSON.stringify(element));
                        },
                });

                //        let table = new DataTable("#report-content");
      });
</script>
</body>

</html>
