<?
/**
 * Upload PDI or Day 30 signed report, and store the filepath to the DB
 * Return JSON array on the result
 */

include "main_include.phtml";
// Return rows for messages
$rtn_rows = array();

$component  = 'PDI';
$reportType = $_POST['reportType'];
$unitNumber  = $_POST['unitNumber'];
$fileName   = $unitNumber . "_" . $reportType . ".png";

// Set up directory
if ($component == 'PDI') {
	$dir = "../images/" . $component . "/";
}

// Check if dir exist, create otherwise
if (!file_exists($dir)) {
    mkdir($dir, 0775);
}

$filepath = $dir . $fileName;

$img = $_POST['imgBase64'];
$img = str_replace('data:image/png;base64,', '', $img);
$img = str_replace(' ', '+', $img);
$fileData = base64_decode($img);
//saving
$result = file_put_contents($filepath, $fileData);

// $result > 0 means number of bytes written
if ($result > 0){
			// Prepare return status
			$rtn_rows['status'] 	= "SUCCESS";
			$rtn_rows['message']	= "Image uploaded successfully";
			$rtn_rows['filepath'] 	= $dir . $filename;
			$rtn_rows['filename']	= $filename;
			$rtn_rows['dirname']	= $dir;

} else {
	$rtn_rows['status']	= "ERROR";
	$rtn_rows['message']= "System error message " . $errors['type'] . " : " . $errors['message'];
}

echo json_encode($rtn_rows);

?>