<?
if ($mode == "CSV") {
    $not_include_javascript = 1;
}
include "main_include.phtml";
include WEB_RESOURCE_INVERT_RELATIVE_PATH . "/framework/URL/LinkGenerator.phtml";

// require UserID & UnitType
// ShowPrice 1/0
// $mode: display, edit, CSV
// 20200813 Allen added download CSV feature
//if (isSet($UserID) && $UserID > 0)
//{
//	// get user info
//	$sql = "SELECT FirstName, LastName, User.UnitNumber AS UnitNumber, Unit.UnitType AS UnitType
//		FROM User
//		LEFT JOIN Unit
//		ON Unit.UserID=User.UserID
//		WHERE User.UserID=$UserID";
//	
//	$user_result = mysql_query($sql,$db) or die("Insert/update failed:\n" . mysql_error() . "\nFull SQL:\n" . $sql . $PHP_SELF);
//	$user_row = mysql_fetch_array($user_result);
//	$UserNumber = $user_row['UserNumber'];
//}

 
if (isSet($UnitNumber) && $UnitNumber > 0)
{
	// get user info
	$sql = "SELECT FirstName, LastName, User.UserID AS UserID, Unit.UnitType AS UnitType, Unit.Model
		FROM Unit
		LEFT JOIN User
		ON User.UnitNumber=Unit.UnitNumber
		AND User.DealStatus != 'Rescinded'
		WHERE Unit.UnitNumber='$UnitNumber'";

	$user_result = mysql_query($sql,$db) or die("Insert/update failed:\n" . mysql_error() . "\nFull SQL:" . $sql . $PHP_SELF);
	$user_row = mysql_fetch_array($user_result);
	$UserID = $user_row['UserID'];
}

$UnitType = $user_row['Model'];

// get info for option chosen
//$sql = "SELECT Price.*, Item.Name As ItemName, Item.ItemID As ItemID, 
//		Section.Name As SectionName, Subsection.Name As SubsectionName,
//		Options.Name As OptionName, Choice.Name As ChoiceName,
//		UserSave.*, DATE_FORMAT(UserSave.IssuedDate, '%b %d, %y' ) AS IssuedDate
//		FROM UserSave, Price, Item, Subsection, Section, Options
//		LEFT JOIN Choice
//		ON UserSave.ChoiceID = Choice.ChoiceID
//		AND UserSave.OptionID = Choice.OptionID
//		WHERE UserSave.UserID = $UserID
//		AND Price.UnitType = '$UnitType'
//		AND UserSave.ItemID = Price.ItemID
//		AND UserSave.OptionID = Price.OptionID
//		AND UserSave.ItemID = Item.ItemID
//		AND Item.SubsectionID = Subsection.SubsectionID
//		AND Subsection.SectionID = Section.SectionID
//		AND UserSave.OptionID = Options.OptionID
//		ORDER BY Section.SectionID, Subsection.SubsectionID, Item.ItemID";
		
		
// use StandardPO table instead of UserSave table
// ALLEN 20151025 Add logic to exlclude items disables in Section
$sql			= " SELECT StandardPO.POID, StandardPO.UnitNumber, StandardPO.ItemID," .
					" StandardPO.OptionID, StandardPO.ChoiceID, StandardPO.ContractorID," .
					" Section.SectionID As SectionID, Subsection.SubsectionID, " .
					" '' AS Description, " .
					" StandardPO.Cost, StandardPO.Issued, StandardPO.IssuedDate, " .
					" Section.Name As SectionName, Subsection.Name As SubsectionName, " .
					" Options.Name As OptionName, Choice.Name As ChoiceName, " .
					" Item.Name As ItemName, Contractor.ContractorName," .
					" 'StandardPO' AS POType" .
					" FROM Contractor, Price, Item, Subsection, Section, Options, Unit, StandardPO " .
					" LEFT JOIN Choice
					ON StandardPO.ChoiceID = Choice.ChoiceID
					AND StandardPO.OptionID = Choice.OptionID
					WHERE StandardPO.ContractorID = Contractor.ContractorID
					AND StandardPO.UnitNumber = '$UnitNumber' 
					AND StandardPO.ItemID = Price.ItemID
					AND StandardPO.OptionID = Price.OptionID
					AND StandardPO.ItemID = Item.ItemID
					AND Item.SubsectionID = Subsection.SubsectionID
					AND Subsection.SectionID = Section.SectionID
					AND StandardPO.OptionID = Options.OptionID
					AND StandardPO.UnitNumber = Unit.UnitNumber
					AND Section.SectionID Not IN (Select SectionID 
						FROM Disable_Section_By_Unittype 
						WHERE Disable_Section_By_Unittype.UnitType = Unit.Model)
					";
 	 
$nonStandardSql = 	" SELECT NonStandardPO.POID, NonStandardPO.UnitNumber, -1 AS ItemID," .
					" -1 AS OptionID, -1 AS ChoiceID, NonStandardPO.ContractorID, " .
					" NonStandardPO.SectionID, NonStandardPO.SubsectionID," .
					" NonStandardPO.Description," .
					" NonStandardPO.Cost, NonStandardPO.Issued, NonStandardPO.IssuedDate," .
					" Section.Name AS SectionName, Subsection.Name AS SubsectionName, " .
					" '' AS OptionName, '' AS ChoiceName, " .
					" '' AS ItemName, Contractor.ContractorName, " .
					" 'NonStandardPO' AS POType" .
					" FROM NonStandardPO, Contractor, Section, Subsection" .
					" WHERE NonStandardPO.SectionID = Section.SectionID " .
					" AND NonStandardPO.UnitNumber = '$UnitNumber' " .
					" AND NonStandardPO.ContractorID = Contractor.ContractorID " .
					" AND NonStandardPO.SubsectionID = Subsection.SubsectionID ";
		
	
$unionSQL = "(" . $sql . " ) UNION (" . $nonStandardSql .
			" ) ORDER BY ContractorID, SectionID, SubsectionID, ItemID";		 		

$price_result = mysql_query($unionSQL,$db) or 
					 die("Insert/update failed:\n" . mysql_error() . "\nFull SQL:<BR>" . $unionSQL . $PHP_SELF);


// get contractor info
$sql = "SELECT ContractorName, ContractorID
		FROM Contractor";

$contractor_result = mysql_query($sql,$db) or die("Insert/update failed:\n" . mysql_error() . "\nFull SQL:<BR>" . $sql . $PHP_SELF);

// generate non standard po edit button
function printNonStandardPOEditButton($POID){
?> <INPUT TYPE="BUTTON" VALUE="EDIT" ONCLICK="displayNonStandardPODIV('edit', <?= $POID; ?>)"><?	
}

function printNonStandardPODeleteButton($POID){
?> <INPUT TYPE="BUTTON" VALUE="Delete" ONCLICK="deleteNonStandardPO(<?= $POID; ?>)"><?	
}

function printNonStandardPOAddButton($POID){
?> <INPUT TYPE="BUTTON" VALUE="Add Non-Standard PO" ONCLICK="displayNonStandardPODIV('add', 0)"><?	
}

if (mysql_num_rows($price_result) <= 0)
{
	die("<br><font face=\"Arial,Verdana,Helvetica\" size=\"3\" color=\"green\"><b>User has not chosen any options yet.</b></font>");
}

if ($mode != "CSV") { ?>
    <html>
    <TITLE>Unit Summary</TITLE>
    <? print_top_frame($PHP_SELF, SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/"); 
    // ALLEN original code which causes issue with the \' in the JS. Remove the \' in the line, and add the quote back at the NonStandardPO page
    //$nonStandardDIVLinkGenerator = new LinkGenerator($PHP_SELF, "nonStandardPO.phtml?UnitNumber=\'$UnitNumber\'", "", "window.parent.editNonStandardPODone()");
    $nonStandardDIVLinkGenerator = new LinkGenerator($PHP_SELF, "nonStandardPO.phtml?UnitNumber=$UnitNumber", "", "window.parent.editNonStandardPODone()");
    ?>
        <script type="text/javascript" src="<?= WEB_RESOURCE_INVERT_RELATIVE_PATH; ?>/javascript/dynamicWindow.js"></script>  
        <script  type="text/javascript" >

            function dumpCSV(){
                window.location='<?= $PHP_SELF; ?>?UnitNumber=<?= $UnitNumber; ?>&ShowPrice=<?= $ShowPrice; ?>&mode=CSV';
            } // dumpCSV

            // reload current page when add/edit non standard PO is done
            function editNonStandardPODone(){
    //			alert("calling editNonStandardPODone");
                window.location.reload();	
            }
            
            // display non standard PO page DIV
            function displayNonStandardPODIV(action, POID){
                newHTML = '<DIV class="popupDiv">';
                newHTML = newHTML + getCloseButton(1);
                newHTML = newHTML + '<IFRAME FRAMEBORDER=0 SRC="<?= $nonStandardDIVLinkGenerator->getDestinationLink(); ?>&action=' + action;
                if (action == 'edit'){
                    newHTML = newHTML + '&POID=' + POID;
                }
                newHTML = newHTML + '" WIDTH=640 HEIGHT=370></IFRAME>'; 
                newHTML = newHTML + '</div>';
    //			alert('newHTML=' + newHTML);
                getFloatingDivNoStyle(1).innerHTML = newHTML;
            
                getFloatingDiv(1).position="absolute";
                getFloatingDiv(1).width="660px";	
                getFloatingDiv(1).height="380px";
                // put it at the center of browser	
                centerDIV(getFloatingDivNoStyle(1));
                // display it
                getFloatingDiv(1).visibility="visible";	
            }
            
            // delete non standard PO Page
            function deleteNonStandardPO(POID){
                var result = confirm('Are you sure you want to delete this Non-Standard PO?');
                if (result){
                    window.location = 'updatePO.phtml?action=delete&poType=nonStandard&UnitNumber=<?= $UnitNumber;?>&POID=' + POID; 
                }	
            }

            // edit individual cost		
            function editIndividualCost(){
                window.location="editUnitUpgradeCost.phtml?UnitNumber=<?= $UnitNumber; ?>"; 	
            }		
        </script>
        



<?
    # Define header colspan depends on display mode
    if ($mode != "display"){ 	
        $headerColSpan = 7; 
    } else { 
        $headerColSpan = 4;
    }
    ?>
    <table>
    <thead>
        <tr>
            <th colspan=<?= $headerColSpan; ?> align="right" class="smalltitle">Name : <?= $user_row['FirstName'] . " " . $user_row['LastName'];?> &nbsp; &nbsp;
            Unit Number : <?= $UnitNumber;?> &nbsp; &nbsp;
            Unit Type : <?= $UnitType;?></th>
        </tr>
    </thead>
    <form id="updatePOForm" method="post" action="updatePO.phtml">
    <input type="hidden" name="action" value="edit"/>
    <input type="hidden" name="poType" value="mix"/>
    <input type="hidden" name="editType" value="issued"/>
    <input type="hidden" name="UserID" value="<?= $UserID; ?>"/>
    <input type="hidden" name="UnitNumber" value="<?= $UnitNumber; ?>"/>
    <tr>
        <td colspan=<?= $headerColSpan; ?> align="right" ><input type="button" value="CSVDownload" ONCLICK="dumpCSV()"/></td>
    </tr>


<? } else { // if mode != CSV 
        $filename = "unitPO.csv";
        $out = fopen ("./" . $filename, "w+") or die("Error: Cannot open " . $filename . " to write");
} // if mode != CSV

$total_cost = 0;
$prev_contractor = "JUNK_DATA";
$prev_PO_type = "JUNK_DATA";

// Print CSV Header
if ($mode == "CSV") {
	fputs ($out, "Trade, POType, Section, Subsection, Option, Choice, Description");

    if ($ShowPrice){ 
        fputs ($out, ",Cost");
    }
    fputs ($out, "\n");

}


while ($price_row = mysql_fetch_array($price_result)){
	if ($price_row['ContractorName'] != $prev_contractor){
		$prev_contractor = $price_row['ContractorName'];
		// reset po type every time a new contractor is displayed 
        $prev_PO_type = "JUNK_DATA";
        
        if ($mode != "CSV") {
?>		
            <tr class="html-space"><td><br><br></td></tr>
            <tr class="fputs ($out, -tr"><td class="fputs ($out, -td" colspan=100><hr class="fputs ($out, -hr"></td></tr> 	
                <tr>
                    <td colspan=100 class="tail-left-med">Trade : <?= $price_row['ContractorName'] ;?></td>
                </tr>
<?      } // mode != CSV
	}


    if ($mode != "CSV") {
            if ($price_row['POType'] != $prev_PO_type){
                    $prev_PO_type = $price_row['POType']; 
                if ($price_row['POType'] == "StandardPO"){
        ?>				<tr class="head">
        <?			if ($mode != "display"){ ?>				
                            <td>Issued</td>
                            <td>Issued Date</td>
        <?			} ?>					
                            <td>Section</td>
                            <td>Subsection</td>
                            <td>Option</td>
                            <td>Choice</td>
                            <? if ($ShowPrice){ ?>
                            <td>Cost</td>
                            <? } ?>
                        </tr>
        <?
                } else {
                    if ($mode != "display"){ 				
        ?>				<tr class="head">
                            <td>Issued</td>
                            <td>Issued Date</td>
        <?					} ?>
                            <td>Section</td>
                            <td>Subsection</td>
                            <td colspan=2>Description</td>
        <? 					if ($ShowPrice){ ?>			
                            <td>Cost</td>
        <? 					} ?>
        <?					if ($mode != "display"){ ?>									
                            <td>Action</td>
        <?					} ?>					
                        </tr>
        <?		}				
            }	
    } // if mode != CSV
        
	$cost = convertPriceConstantToValidNumber($price_row['Cost']);
	// a standarized way to display PO Issue checkbox
			
    if ($mode != "CSV") {
	    if ($price_row['POType'] == "StandardPO"){
            if ($mode != "display"){ 				
    ?>				<td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><? printStandardPOIssueCheckBox(array("itemID"=>$price_row['ItemID'], "optionID"=>$price_row['OptionID'], "issued"=>$price_row['Issued'])); ?></td>
                    <td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= $price_row['IssuedDate'];?></td>
    <?		} ?>
                    <td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= $price_row['SectionName'];?></td>
                    <td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= $price_row['SubsectionName'];?></td>
                    <td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= $price_row['OptionName'];?></td>
                    <td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= $price_row['ChoiceName'];?></td>
                    <? if ($ShowPrice){
                        $total_cost += convertPriceConstantToValidNumber($price_row['Cost']); ?>					 
                    <td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= convertPriceConstantToString($price_row['Cost']); ?></td>
                    <? } ?>
                    
			</tr>
            <?
	    } else { // Non Standard PO
			if ($mode != "display"){ ?>				
				<td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><? printNonStandardPOIssueCheckBox(array("POID" =>$price_row['POID'], "issued"=>$price_row['Issued'])); ?></td>				
				<td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= $price_row['IssuedDate'];?></td>
<?			} ?>
				<td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= $price_row['SectionName'];?></td>
				<td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= $price_row['SubsectionName'];?></td>
				<td  <?= ($cost>0 ? 'class="tdI"' : ''); ?> colspan=2><?= $price_row['Description'];?></td>
<? 				if ($ShowPrice){ 		
					$total_cost += convertPriceConstantToValidNumber($price_row['Cost']); ?>
				<td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><?= convertPriceConstantToString($price_row['Cost']);?></td>
<? 				} ?>
<?				if ($mode != "display"){ ?>								
				<td <?= ($cost>0 ? 'class="tdI"' : ''); ?>><? printNonStandardPOEditButton($price_row['POID']); ?><? printNonStandardPODeleteButton($price_row['POID']); ?></td>
<?				} ?>				
			</tr>
<?      }            
    } else {
        if ($price_row['POType'] == "StandardPO"){
            fputs ($out, "\"" . $price_row['ContractorName'] . "\"");
            fputs ($out,  ",\"StandardPO\"");
            fputs ($out,  ",\"" . $price_row['SectionName'] . "\"");
            fputs ($out,  ",\"" . $price_row['SubsectionName'] . "\"");
            fputs ($out,  ",\"" . $price_row['OptionName'] . "\"");
            fputs ($out,  ",\"" . $price_row['ChoiceName'] . "\"");
            fputs ($out,  ",\"\"");

            if ($ShowPrice) {
                fputs ($out,  ",\"" . convertPriceConstantToString($price_row['Cost']) . "\"");
                $total_cost += $cost;
            }
            fputs ($out,  "\n");
        } else {
            fputs ($out,  "\"" . $price_row['ContractorName'] . "\"");
            fputs ($out,  ",\"NonStandardPO\"");
            fputs ($out,  ",\"" . $price_row['SectionName'], "\"");
            fputs ($out,  ",\"" . $price_row['SubsectionName'] . "\"");
            fputs ($out,  ",\"\"" );
            fputs ($out,  ",\"\"" );
            fputs ($out,  ",\"\"" );
            fputs ($out,  ",\"" . $price_row['Description'] . "\"");

            if ($ShowPrice) {
                fputs ($out,  ",\"" . convertPriceConstantToString($price_row['Cost']) . "\"");
                $total_cost += $cost;
            }
            fputs ($out,  "\n");
        }
    }
} // While loop
	
if ($ShowPrice){ 		
    if ($mode != "CSV") {
?>
	<tr>
		<td colspan=100><BR><BR><hr></td>
	</tr>

	<tr>
		<td colspan=5></td>
		<td><b>Total</b></td>
		<td><?= $total_cost; ?></td>
	</tr>
	<tr>
		<td colspan=100><hr></td>
	</tr>

<?  } else { // CSV mode
        fputs ($out,  "Total,,,,,,," . $total_cost);
        fputs ($out,  "\n");
    }
} 



if ($mode != "CSV") { ?>
	<tr><td><br><br></td></tr>
<?	
    if ($mode == "edit" ){ ?>				
        <TR class="button"><td colspan=100>
        <INPUT type="submit" Value="Update">
        &nbsp;&nbsp;<INPUT type="button" Value="Edit Individual Cost for Standard PO" onClick="editIndividualCost();">
        &nbsp;&nbsp;<? printNonStandardPOAddButton(); ?> </td></tr>
    <?	} ?>
    </form>
    </table>
    </html>
<? } else { 
    fclose($out);
    header('Content-type: application/excel');
    header('Content-Disposition: attachment; filename="' . $filename . '"');    


    if(strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE'))
    {
        header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        header('Pragma: public');
    } 
    
    readfile($filename);

} // mode != csv