<?
/**
* Upload file to server via AJAX call
*/
include "main_include.phtml";

$dir = "../image/";
$filename = "PDI_TEST.jpg";


$rtn_rows = array();

if (!isset($myFile) || $myFile == "none")
{
	//echo "Upload file invalid.";
	$rtn_rows['status']	= "ERROR";
	$rtn_rows['message']= "File is invalid.";	
	echo json_encode($rtn_rows);
	return;
}




			
				
//	if (!move_uploaded_file($myFile, $dir . $filename)) {
	if (!copy($myFile, $dir . $filename)) {
			//echo "Upload to $dir.$filename failed.";
			$rtn_rows['status']	= "ERROR";
			$rtn_rows['message']= "Upload to " . $dir . $filename . " failed.";
	} else {
		if ($table_name == "Choice"){
			// update DB
			$sql = "UPDATE " . $table_name . 
					" SET ImageName=\"" . $filename . "\" WHERE " .
					" ChoiceID=$ChoiceID";
			$result = mysql_query($sql) or die("ERROR : $sql <br>" . mysql_error());	
		}

			$rtn_row['status'] 	= "SUCCESS";
			$rtn_row['message']	= "Upload successfully to $dir.$filename failed.";

			//echo "Upload Successfully.";
	}
echo json_encode($rtn_rows);
?>