CREATE TABLE Floorplan (
    FPID        INT AUTO_INCREMENT PRIMARY KEY,
    ImagePath   VARCHAR(255) NOT NULL,
    ImageMap    VARCHAR(999),
    CreatedAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt  TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB;


ALTER TABLE Unit ADD FPID INT DEFAULT NULL;
