<?php
/*
 * Created on 21-Jan-2006
 *
 * Config error handling for ErrorHandler class
 * $errorHandler->loadErrorDataFile(LOCAL_CONFIG_FOLDER . "/errorCofig.phtml"); 
 **/
 
// all constant is defined in the config.phtml in the same folder
$this->registerErrorData(SESSION_EXPIRED, "/lmark/hazelton/highlight/RealEstateDB/index.phtml", "Session has expired. Please login again.");
$this->registerErrorData(LOGIN_INVALID, "/lmark/hazelton/highlight/RealEstateDB/index.phtml", "Invalid login/password. Please try again.");
$this->registerErrorData(COMMIT_ALREADY, "/lmark/hazelton/highlight/RealEstateDB/preview.phtml", "Error. Cannot make changes once a commitment has been made.");
$this->registerErrorData(SQL_ERROR, "/lmark/hazelton/highlight/RealEstateDB/error.phtml", "There is a database error. Please try again later or contact ofice.");
//$this->registerErrorData(SQL_ERROR, "error.phtml", "HELLO");
$this->registerErrorData(GENERAL_ERROR, "/lmark/hazelton/highlight/RealEstateDB/error.phtml", "Error");

?>
